spring.application.name=launchpad

# JPA and DB
spring.datasource.url=jdbc:postgresql://localhost:5432/launchpad
spring.datasource.username=launchpad
spring.datasource.password=launchpad
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
logging.level.com.launchpad.config=DEBUG